-------------------------------------------------------Normandy DataBAseAiports BY BAZTIAN-----------------------------------------------------------------------------------------------------------------------------------------------------

estadoBanderasAeropuertos = {
    ["Bitburg"] = { bandera = 100, valor = nil },
    ["Spangdahlem"] = { bandera = 101, valor = nil },
    ["Ramstein"] = { bandera = 102, valor = nil },
    ["Buchel"] = { bandera = 103, valor = nil },
    ["Wiesbaden"] = { bandera = 104, valor = nil },
    ["Buckeburg"] = { bandera = 105, valor = nil },
    ["Hahn"] = { bandera = 106, valor = nil },
    ["mending"] = { bandera = 107, valor = nil },
    ["Pferdsfeld"] = { bandera = 108, valor = nil },
    ["Zweibrucken"] = { bandera = 109, valor = nil },
    ["Frankfurt"] = { bandera = 110, valor = nil },
    ["Giebelstadt"] = { bandera = 111, valor = nil },
    ["Scheweinfurt"] = { bandera = 112, valor = nil },
    ["Gutersloh"] = { bandera = 113, valor = nil },
    ["Hildesheim"] = { bandera = 114, valor = nil },
    ["Braunschweig"] = { bandera = 115, valor = nil },
    ["Celle"] = { bandera = 116, valor = nil },
    ["Fassberg"] = { bandera = 117, valor = nil },
    ["Bremen"] = { bandera = 118, valor = nil },
    ["Hamburg Finkenwerder"] = { bandera = 119, valor = nil },
    ["Hamburg"] = { bandera = 120, valor = nil },
    ["Lubeck"] = { bandera = 121, valor = nil },
    ["Wunstorf"] = { bandera = 122, valor = nil },
    ["Hannover"] = { bandera = 123, valor = nil },
    ["Haina"] = { bandera = 124, valor = nil },
    ["Obermehler Schlotheim"] = { bandera = 125, valor = nil },
    ["Bindersleben"] = { bandera = 126, valor = nil },
    ["Allstedt"] = { bandera = 127, valor = nil },
    ["Merseburg"] = { bandera = 128, valor = nil },
    ["Leipzig Halle"] = { bandera = 129, valor = nil },
    ["Leipzig Mockau"] = { bandera = 130, valor = nil },
    ["Cochstedt"] = { bandera = 131, valor = nil },
    ["Kothen"] = { bandera = 132, valor = nil },
    ["Dessau"] = { bandera = 133, valor = nil },
    ["Leipzig Halle"] = { bandera = 134, valor = nil },
    ["Zerbst"] = { bandera = 135, valor = nil },
    ["Altes Lager"] = { bandera = 136, valor = nil },
    ["Sperenberg"] = { bandera = 137, valor = nil },
    ["Holzdorf"] = { bandera = 138, valor = nil },
    ["Mahlwinkel"] = { bandera = 139, valor = nil },
    ["Stendal"] = { bandera = 140, valor = nil },
    ["Neuruppin"] = { bandera = 141, valor = nil },
    ["Gatow"] = { bandera = 142, valor = nil },
    ["Tegel"] = { bandera = 143, valor = nil },
    ["Tempelhof"] = { bandera = 144, valor = nil },
    ["Templin"] = { bandera = 145, valor = nil },
    ["Schonefeld"] = { bandera = 146, valor = nil },
    ["Werneuchen"] = { bandera = 147, valor = nil },
    ["Finow"] = { bandera = 148, valor = nil },
    ["Wittstock"] = { bandera = 149, valor = nil },
    ["Parchim"] = { bandera = 150, valor = nil },
    ["Tutow"] = { bandera = 151, valor = nil },
    ["Laage"] = { bandera = 152, valor = nil },
    ["Larz"] = { bandera = 153, valor = nil },
    ["Neubrandenburg"] = { bandera = 154, valor = nil },
    ["Garz"] = { bandera = 155, valor = nil },
    ["Peenemunde"] = { bandera = 156, valor = nil },
    ["Damgarten"] = { bandera = 157, valor = nil }
}

aeropuertos = {
    ["Kenley"] = { position = {x = 202873, y = 0, z = 6965}, radius = 6000 },
    ["Ford"] = { position = {x = 147466, y = 0, z = -25753}, radius = 5000 },
    ["Friston"] = { position = {x = 143314, y = 0, z = 28130}, radius = 5000 },
    ["Maupertus"] = { position = {x = 16011, y = 0, z = -84865}, radius = 6000 },
    ["Brucheville"] = { position = {x = -14865, y = 0, z = -66032}, radius = 5000 },
    ["Carpiquet"] = { position = {x = -34775, y = 0, z = -9992}, radius = 6000 },
    ["Ronai"] = { position = {x = -73108, y = 0, z = 12832}, radius = 5000 },
    ["Bernay Saint Martin"] = { position = {x = -39530, y = 0, z = 67036}, radius = 5000 },
    ["Barville"] = { position = {x = -109836, y = 0, z = 49213}, radius = 4000 },
    ["Evreux"] = { position = {x = -45924, y = 0, z = 112428}, radius = 4000 },
    ["Orly"] = { position = {x = -73529, y = 0, z = 200430}, radius = 12000 },
    ["Fecamp-Benouville"] = { position = {x = 31004, y = 0, z = 46274}, radius = 4000 },
    ["Saint-Aubin"] = { position = {x = 48979, y = 0, z = 97582}, radius = 4000 },
    ["Beauvais-Tille"] = { position = {x = 6070, y = 0, z = 175169}, radius = 5000 },
    ["Amiens-Glisy"] = { position = {x = 53411, y = 0, z = 191760}, radius = 5000 },
    ["Abbeville Drucat"] = { position = {x = 81026, y = 0, z = 150752}, radius = 5000 }
}